---

- name: Create /opt/source/wordpress directory
  become: yes
#  command: mkdir -p /opt/source/wordpress
  file:
    path: /opt/source/wordpress
    state: directory

- name: Download Wordpress
  become: true
  get_url:
    url: "https://www.wordpress.org/latest.tar.gz"
    dest: "/opt/source/wordpress/wordpress.tar.gz"
    validate_certs: no

- name: Extract downloaded archive
  become: yes
  unarchive:
    src: /opt/source/wordpress/wordpress.tar.gz
    remote_src: yes
    dest: /var/www/html
#    extra_opts="strip-components=1"
    extra_opts:
      - "--strip-components=1"

- name: Copy Wordpress config file
  become: yes
  template:
    src: "wp-config-default.php.j2"
    dest: "/var/www/html/wp-config.php"
    owner: root
    group: root

- name: Ensure Apache service is restarted
  become: yes
  service:
    name: httpd
    state: restarted
    enabled: yes
